<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ihs extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ihs_model');
    } 

    /*
     * Listing of ihs
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('ihs/index?');
        $config['total_rows'] = $this->Ihs_model->get_all_ihs_count();
        $this->pagination->initialize($config);

        $data['ihs'] = $this->Ihs_model->get_all_ihs($params);
        
        $data['_view'] = 'ihs/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new ihs
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('mnemonikCode','MnemonikCode','integer');
		$this->form_validation->set_rules('oemGroup','OemGroup','max_length[45]');
		$this->form_validation->set_rules('oem','Oem','max_length[45]');
		$this->form_validation->set_rules('customerplant','Customerplant','max_length[45]');
		$this->form_validation->set_rules('vehicle','Vehicle','max_length[45]');
		$this->form_validation->set_rules('program','Program','max_length[45]');
		$this->form_validation->set_rules('platform','Platform','max_length[45]');
		$this->form_validation->set_rules('region','Region','max_length[45]');
		$this->form_validation->set_rules('sop','Sop','max_length[45]');
		$this->form_validation->set_rules('eop','Eop','max_length[45]');
		$this->form_validation->set_rules('bodystyle','Bodystyle','max_length[45]');
		$this->form_validation->set_rules('bodytype','Bodytype','max_length[45]');
		$this->form_validation->set_rules('productionNameplate','ProductionNameplate','max_length[45]');
		$this->form_validation->set_rules('productionBrand','ProductionBrand','max_length[45]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'mnemonikCode' => $this->input->post('mnemonikCode'),
				'oemGroup' => $this->input->post('oemGroup'),
				'oem' => $this->input->post('oem'),
				'customerplant' => $this->input->post('customerplant'),
				'vehicle' => $this->input->post('vehicle'),
				'program' => $this->input->post('program'),
				'platform' => $this->input->post('platform'),
				'region' => $this->input->post('region'),
				'sop' => $this->input->post('sop'),
				'eop' => $this->input->post('eop'),
				'bodystyle' => $this->input->post('bodystyle'),
				'bodytype' => $this->input->post('bodytype'),
				'productionNameplate' => $this->input->post('productionNameplate'),
				'productionBrand' => $this->input->post('productionBrand'),
            );
            
            $ihs_id = $this->Ihs_model->add_ihs($params);
            redirect('ihs/index');
        }
        else
        {            
            $data['_view'] = 'ihs/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a ihs
     */
    function edit($idIHS)
    {   
        // check if the ihs exists before trying to edit it
        $data['ihs'] = $this->Ihs_model->get_ihs($idIHS);
        
        if(isset($data['ihs']['idIHS']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('mnemonikCode','MnemonikCode','integer');
			$this->form_validation->set_rules('oemGroup','OemGroup','max_length[45]');
			$this->form_validation->set_rules('oem','Oem','max_length[45]');
			$this->form_validation->set_rules('customerplant','Customerplant','max_length[45]');
			$this->form_validation->set_rules('vehicle','Vehicle','max_length[45]');
			$this->form_validation->set_rules('program','Program','max_length[45]');
			$this->form_validation->set_rules('platform','Platform','max_length[45]');
			$this->form_validation->set_rules('region','Region','max_length[45]');
			$this->form_validation->set_rules('sop','Sop','max_length[45]');
			$this->form_validation->set_rules('eop','Eop','max_length[45]');
			$this->form_validation->set_rules('bodystyle','Bodystyle','max_length[45]');
			$this->form_validation->set_rules('bodytype','Bodytype','max_length[45]');
			$this->form_validation->set_rules('productionNameplate','ProductionNameplate','max_length[45]');
			$this->form_validation->set_rules('productionBrand','ProductionBrand','max_length[45]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'mnemonikCode' => $this->input->post('mnemonikCode'),
					'oemGroup' => $this->input->post('oemGroup'),
					'oem' => $this->input->post('oem'),
					'customerplant' => $this->input->post('customerplant'),
					'vehicle' => $this->input->post('vehicle'),
					'program' => $this->input->post('program'),
					'platform' => $this->input->post('platform'),
					'region' => $this->input->post('region'),
					'sop' => $this->input->post('sop'),
					'eop' => $this->input->post('eop'),
					'bodystyle' => $this->input->post('bodystyle'),
					'bodytype' => $this->input->post('bodytype'),
					'productionNameplate' => $this->input->post('productionNameplate'),
					'productionBrand' => $this->input->post('productionBrand'),
                );

                $this->Ihs_model->update_ihs($idIHS,$params);            
                redirect('ihs/index');
            }
            else
            {
                $data['_view'] = 'ihs/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The ihs you are trying to edit does not exist.');
    } 

    /*
     * Deleting ihs
     */
    function remove($idIHS)
    {
        $ihs = $this->Ihs_model->get_ihs($idIHS);

        // check if the ihs exists before trying to delete it
        if(isset($ihs['idIHS']))
        {
            $this->Ihs_model->delete_ihs($idIHS);
            redirect('ihs/index');
        }
        else
            show_error('The ihs you are trying to delete does not exist.');
    }
    
}
