<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class News extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('News_model');
    } 

    /*
     * Listing of news
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('news/index?');
        $config['total_rows'] = $this->News_model->get_all_news_count();
        $this->pagination->initialize($config);

        $data['news'] = $this->News_model->get_all_news($params);
        
        $data['_view'] = 'news/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new news
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('header','Header','max_length[120]');
		$this->form_validation->set_rules('news','News','max_length[1024]');
		$this->form_validation->set_rules('date','Date','max_length[45]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'header' => $this->input->post('header'),
				'news' => $this->input->post('news'),
				'date' => $this->input->post('date'),
            );
            
            $news_id = $this->News_model->add_news($params);
            redirect('news/index');
        }
        else
        {            
            $data['_view'] = 'news/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a news
     */
    function edit($idNews)
    {   
        // check if the news exists before trying to edit it
        $data['news'] = $this->News_model->get_news($idNews);
        
        if(isset($data['news']['idNews']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('header','Header','max_length[120]');
			$this->form_validation->set_rules('news','News','max_length[1024]');
			$this->form_validation->set_rules('date','Date','max_length[45]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'header' => $this->input->post('header'),
					'news' => $this->input->post('news'),
					'date' => $this->input->post('date'),
                );

                $this->News_model->update_news($idNews,$params);            
                redirect('news/index');
            }
            else
            {
                $data['_view'] = 'news/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The news you are trying to edit does not exist.');
    } 

    /*
     * Deleting news
     */
    function remove($idNews)
    {
        $news = $this->News_model->get_news($idNews);

        // check if the news exists before trying to delete it
        if(isset($news['idNews']))
        {
            $this->News_model->delete_news($idNews);
            redirect('news/index');
        }
        else
            show_error('The news you are trying to delete does not exist.');
    }
    
}
