<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sap extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sap_model');
    } 

    /*
     * Listing of sap
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('sap/index?');
        $config['total_rows'] = $this->Sap_model->get_all_sap_count();
        $this->pagination->initialize($config);

        $data['sap'] = $this->Sap_model->get_all_sap($params);
        
        $data['_view'] = 'sap/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sap
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('materialNumber','MaterialNumber','max_length[45]');
		$this->form_validation->set_rules('debitor','Debitor','max_length[45]');
		$this->form_validation->set_rules('debitorName','DebitorName','max_length[45]');
		$this->form_validation->set_rules('vkorg','Vkorg','integer');
		$this->form_validation->set_rules('werk','Werk','integer');
		$this->form_validation->set_rules('vtrwg','Vtrwg','integer');
		$this->form_validation->set_rules('productGroup','ProductGroup','max_length[45]');
		$this->form_validation->set_rules('shortnumber','Shortnumber','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'materialNumber' => $this->input->post('materialNumber'),
				'debitor' => $this->input->post('debitor'),
				'debitorName' => $this->input->post('debitorName'),
				'vkorg' => $this->input->post('vkorg'),
				'werk' => $this->input->post('werk'),
				'vtrwg' => $this->input->post('vtrwg'),
				'productGroup' => $this->input->post('productGroup'),
				'shortnumber' => $this->input->post('shortnumber'),
            );
            
            $sap_id = $this->Sap_model->add_sap($params);
            redirect('sap/index');
        }
        else
        {            
            $data['_view'] = 'sap/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sap
     */
    function edit($idSAP)
    {   
        // check if the sap exists before trying to edit it
        $data['sap'] = $this->Sap_model->get_sap($idSAP);
        
        if(isset($data['sap']['idSAP']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('materialNumber','MaterialNumber','max_length[45]');
			$this->form_validation->set_rules('debitor','Debitor','max_length[45]');
			$this->form_validation->set_rules('debitorName','DebitorName','max_length[45]');
			$this->form_validation->set_rules('vkorg','Vkorg','integer');
			$this->form_validation->set_rules('werk','Werk','integer');
			$this->form_validation->set_rules('vtrwg','Vtrwg','integer');
			$this->form_validation->set_rules('productGroup','ProductGroup','max_length[45]');
			$this->form_validation->set_rules('shortnumber','Shortnumber','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'materialNumber' => $this->input->post('materialNumber'),
					'debitor' => $this->input->post('debitor'),
					'debitorName' => $this->input->post('debitorName'),
					'vkorg' => $this->input->post('vkorg'),
					'werk' => $this->input->post('werk'),
					'vtrwg' => $this->input->post('vtrwg'),
					'productGroup' => $this->input->post('productGroup'),
					'shortnumber' => $this->input->post('shortnumber'),
                );

                $this->Sap_model->update_sap($idSAP,$params);            
                redirect('sap/index');
            }
            else
            {
                $data['_view'] = 'sap/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sap you are trying to edit does not exist.');
    } 

    /*
     * Deleting sap
     */
    function remove($idSAP)
    {
        $sap = $this->Sap_model->get_sap($idSAP);

        // check if the sap exists before trying to delete it
        if(isset($sap['idSAP']))
        {
            $this->Sap_model->delete_sap($idSAP);
            redirect('sap/index');
        }
        else
            show_error('The sap you are trying to delete does not exist.');
    }
    
}
