<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_role extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_role_model');
    }
}
