-- MySQL Workbench Synchronization
-- Generated: 2018-06-13 10:23
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: KuhnL

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `vehiclebom`.`IHS` (
  `idIHS` INT(11) NOT NULL AUTO_INCREMENT,
  `mnemonikCode` INT(11) NULL DEFAULT NULL,
  `oemGroup` VARCHAR(45) NULL DEFAULT NULL,
  `oem` VARCHAR(45) NULL DEFAULT NULL,
  `customerplant` VARCHAR(45) NULL DEFAULT NULL,
  `vehicle` VARCHAR(45) NULL DEFAULT NULL,
  `program` VARCHAR(45) NULL DEFAULT NULL,
  `platform` VARCHAR(45) NULL DEFAULT NULL,
  `region` VARCHAR(45) NULL DEFAULT NULL,
  `sop` VARCHAR(45) NULL DEFAULT NULL,
  `eop` VARCHAR(45) NULL DEFAULT NULL,
  `bodystyle` VARCHAR(45) NULL DEFAULT NULL,
  `bodytype` VARCHAR(45) NULL DEFAULT NULL,
  `productionNameplate` VARCHAR(45) NULL DEFAULT NULL,
  `productionBrand` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idIHS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `vehiclebom`.`SAP` (
  `idSAP` INT(11) NOT NULL AUTO_INCREMENT,
  `materialNumber` VARCHAR(45) NULL DEFAULT NULL,
  `debitor` VARCHAR(45) NULL DEFAULT NULL,
  `debitorName` VARCHAR(45) NULL DEFAULT NULL,
  `vkorg` INT(11) NULL DEFAULT NULL,
  `werk` INT(11) NULL DEFAULT NULL,
  `vtrwg` INT(11) NULL DEFAULT NULL,
  `productGroup` VARCHAR(45) NULL DEFAULT NULL,
  `shortnumber` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idSAP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `vehiclebom`.`VolumeSource` (
  `idVolumeSource` INT(11) NOT NULL AUTO_INCREMENT,
  `idIHS` INT(11) NULL DEFAULT NULL,
  `idUser` INT(11) NULL DEFAULT NULL,
  `active` VARCHAR(45) NULL DEFAULT NULL,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  `volumeName` VARCHAR(45) NULL DEFAULT NULL,
  `source` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idVolumeSource`),
  INDEX `fk_VolumeSource_IHS_idx` (`idIHS` ASC),
  CONSTRAINT `fk_VolumeSource_IHS`
    FOREIGN KEY (`idIHS`)
    REFERENCES `vehiclebom`.`IHS` (`idIHS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `vehiclebom`.`VolumeYears` (
  `idVolumeYears` INT(11) NOT NULL AUTO_INCREMENT,
  `idVolumeSource` INT(11) NULL DEFAULT NULL,
  `year` INT(11) NULL DEFAULT NULL,
  `volume` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idVolumeYears`),
  INDEX `fk_VolumeYears_VolumeSource1_idx` (`idVolumeSource` ASC),
  CONSTRAINT `fk_VolumeYears_VolumeSource1`
    FOREIGN KEY (`idVolumeSource`)
    REFERENCES `vehiclebom`.`VolumeSource` (`idVolumeSource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `vehiclebom`.`VolumeMonth` (
  `idVolumeMonth` INT(11) NOT NULL AUTO_INCREMENT,
  `idVolumeYears` INT(11) NULL DEFAULT NULL,
  `Month` INT(11) NULL DEFAULT NULL,
  `year` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idVolumeMonth`),
  INDEX `fk_VolumeMonth_VolumeYears1_idx` (`idVolumeYears` ASC),
  CONSTRAINT `fk_VolumeMonth_VolumeYears1`
    FOREIGN KEY (`idVolumeYears`)
    REFERENCES `vehiclebom`.`VolumeYears` (`idVolumeYears`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `vehiclebom`.`BOM` (
  `idBOM` INT(11) NOT NULL AUTO_INCREMENT,
  `idIHS` INT(11) NULL DEFAULT NULL,
  `idSAP` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idBOM`),
  INDEX `fk_BOM_IHS1_idx` (`idIHS` ASC),
  INDEX `fk_BOM_SAP1_idx` (`idSAP` ASC),
  CONSTRAINT `fk_BOM_IHS1`
    FOREIGN KEY (`idIHS`)
    REFERENCES `vehiclebom`.`IHS` (`idIHS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BOM_SAP1`
    FOREIGN KEY (`idSAP`)
    REFERENCES `vehiclebom`.`SAP` (`idSAP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `vehiclebom`.`TakeRate` (
  `idTakeRate` INT(11) NOT NULL AUTO_INCREMENT,
  `idBOM` INT(11) NULL DEFAULT NULL,
  `idUser` INT(11) NULL DEFAULT NULL,
  `year` INT(11) NULL DEFAULT NULL,
  `takeRate` INT(11) NULL DEFAULT NULL,
  `deliveryQuote` INT(11) NULL DEFAULT NULL,
  `numberPerCar` INT(11) NULL DEFAULT NULL,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTakeRate`),
  INDEX `fk_TakeRate_BOM1_idx` (`idBOM` ASC),
  CONSTRAINT `fk_TakeRate_BOM1`
    FOREIGN KEY (`idBOM`)
    REFERENCES `vehiclebom`.`BOM` (`idBOM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `vehiclebom`.`News` (
  `idNews` INT(11) NOT NULL,
  `header` VARCHAR(120) NULL DEFAULT NULL,
  `news` VARCHAR(1024) NULL DEFAULT NULL,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idNews`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
