<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bom_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bom by idBOM
     */
    function get_bom($idBOM)
    {
        return $this->db->get_where('bom',array('idBOM'=>$idBOM))->row_array();
    }
    
    /*
     * Get all bom count
     */
    function get_all_bom_count()
    {
        $this->db->from('bom');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all bom
     */
    function get_all_bom($params = array())
    {
        $this->db->order_by('idBOM', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('bom')->result_array();
    }
        
    /*
     * function to add new bom
     */
    function add_bom($params)
    {
        $this->db->insert('bom',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bom
     */
    function update_bom($idBOM,$params)
    {
        $this->db->where('idBOM',$idBOM);
        return $this->db->update('bom',$params);
    }
    
    /*
     * function to delete bom
     */
    function delete_bom($idBOM)
    {
        return $this->db->delete('bom',array('idBOM'=>$idBOM));
    }
}
