<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ihs_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ihs by idIHS
     */
    function get_ihs($idIHS)
    {
        return $this->db->get_where('ihs',array('idIHS'=>$idIHS))->row_array();
    }
    
    /*
     * Get all ihs count
     */
    function get_all_ihs_count()
    {
        $this->db->from('ihs');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all ihs
     */
    function get_all_ihs($params = array())
    {
        $this->db->order_by('idIHS', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('ihs')->result_array();
    }
        
    /*
     * function to add new ihs
     */
    function add_ihs($params)
    {
        $this->db->insert('ihs',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ihs
     */
    function update_ihs($idIHS,$params)
    {
        $this->db->where('idIHS',$idIHS);
        return $this->db->update('ihs',$params);
    }
    
    /*
     * function to delete ihs
     */
    function delete_ihs($idIHS)
    {
        return $this->db->delete('ihs',array('idIHS'=>$idIHS));
    }
}
