<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class News_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get news by idNews
     */
    function get_news($idNews)
    {
        return $this->db->get_where('news',array('idNews'=>$idNews))->row_array();
    }
    
    /*
     * Get all news count
     */
    function get_all_news_count()
    {
        $this->db->from('news');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all news
     */
    function get_all_news($params = array())
    {
        $this->db->order_by('idNews', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('news')->result_array();
    }
        
    /*
     * function to add new news
     */
    function add_news($params)
    {
        $this->db->insert('news',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update news
     */
    function update_news($idNews,$params)
    {
        $this->db->where('idNews',$idNews);
        return $this->db->update('news',$params);
    }
    
    /*
     * function to delete news
     */
    function delete_news($idNews)
    {
        return $this->db->delete('news',array('idNews'=>$idNews));
    }
}
