<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sap_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sap by idSAP
     */
    function get_sap($idSAP)
    {
        return $this->db->get_where('sap',array('idSAP'=>$idSAP))->row_array();
    }
    
    /*
     * Get all sap count
     */
    function get_all_sap_count()
    {
        $this->db->from('sap');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all sap
     */
    function get_all_sap($params = array())
    {
        $this->db->order_by('idSAP', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('sap')->result_array();
    }
        
    /*
     * function to add new sap
     */
    function add_sap($params)
    {
        $this->db->insert('sap',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sap
     */
    function update_sap($idSAP,$params)
    {
        $this->db->where('idSAP',$idSAP);
        return $this->db->update('sap',$params);
    }
    
    /*
     * function to delete sap
     */
    function delete_sap($idSAP)
    {
        return $this->db->delete('sap',array('idSAP'=>$idSAP));
    }
}
