<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Volumesource_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get volumesource by idVolumeSource
     */
    function get_volumesource($idVolumeSource)
    {
        return $this->db->get_where('volumesource',array('idVolumeSource'=>$idVolumeSource))->row_array();
    }
    
    /*
     * Get all volumesource count
     */
    function get_all_volumesource_count()
    {
        $this->db->from('volumesource');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all volumesource
     */
    function get_all_volumesource($params = array())
    {
        $this->db->order_by('idVolumeSource', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('volumesource')->result_array();
    }
        
    /*
     * function to add new volumesource
     */
    function add_volumesource($params)
    {
        $this->db->insert('volumesource',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update volumesource
     */
    function update_volumesource($idVolumeSource,$params)
    {
        $this->db->where('idVolumeSource',$idVolumeSource);
        return $this->db->update('volumesource',$params);
    }
    
    /*
     * function to delete volumesource
     */
    function delete_volumesource($idVolumeSource)
    {
        return $this->db->delete('volumesource',array('idVolumeSource'=>$idVolumeSource));
    }
}
