<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Volumemonth_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get volumemonth by idVolumeMonth
     */
    function get_volumemonth($idVolumeMonth)
    {
        return $this->db->get_where('volumemonth',array('idVolumeMonth'=>$idVolumeMonth))->row_array();
    }
    
    /*
     * Get all volumemonth count
     */
    function get_all_volumemonth_count()
    {
        $this->db->from('volumemonth');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all volumemonth
     */
    function get_all_volumemonth($params = array())
    {
        $this->db->order_by('idVolumeMonth', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('volumemonth')->result_array();
    }
        
    /*
     * function to add new volumemonth
     */
    function add_volumemonth($params)
    {
        $this->db->insert('volumemonth',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update volumemonth
     */
    function update_volumemonth($idVolumeMonth,$params)
    {
        $this->db->where('idVolumeMonth',$idVolumeMonth);
        return $this->db->update('volumemonth',$params);
    }
    
    /*
     * function to delete volumemonth
     */
    function delete_volumemonth($idVolumeMonth)
    {
        return $this->db->delete('volumemonth',array('idVolumeMonth'=>$idVolumeMonth));
    }
}
